# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.7
python: 3.7

# Install project dependencies
install:
  - make requirements-dev

# Run the unit test
script:
  - make lint
  - make test-coverage
  - make check-vulnerabilities

after_success:
  - make test-coverage
