# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.7
python: 3.8

# Install project dependencies
install:
  - make requirements-dev

# Run the unit test
script:
  - make lint
  - make check-vulnerabilities
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
