swagger: "2.0"
info:
  description: API responsible for managing and searching drink partners
  version: "0.6.0"
  title: drink_partners
basePath: /
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /partner/{id}/:
    get:
      tags:
        - partner
      summary: Returns a partner by its id
      description: Returns a partner by its id
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: success
        "404":
          description: not_found
        "400":
          description: bad_request
      parameters:
        - in: "path"
          name: "id"
          description: "Partner id"
          required: true
          type: "string"